### ISSUE TITLE
Add Canadian football field

### ISSUE THREAD

**Issue by christophermclement** [nguyenank/shot-plotter#20]
Add a Canadian football field option. Identical functionality as NFL/NCAA football, using a different underlying field. sportyR has a CFL field with 24-yd hashes, there is also a need for one with 28-yd hashes, that can be derived with 
`field_updates = list("inbound_cross_hash_separation" = 9, "inbound_hashmark_separation" = 7.6667)`
per rossdrucker.

**Comment by nguyenank** [comment]
Alright, sounds good. Could you explain the difference between the different hashes (just so I know how to label them)?

**Comment by christophermclement** [comment]
One set is 24 yds from the sideline and should be labelled something like "CFL pre-2022 & Amateur," the other set are 28 yards from the sideline and should be labelled "CFL post-2022"
